language: php

dist: trusty

env:
  global:
    - COMPOSER_ROOT_VERSION=1.x-dev

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DB=PGSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL PDO=1 PHPUNIT_COVERAGE_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL PHPUNIT_TEST=1

before_script:
# Init PHP
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer
  - composer validate
  - composer install --prefer-dist
  - composer require silverstripe/recipe-cms:4.5.x-dev --prefer-dist --no-update
  - composer update
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.1.x-dev --prefer-dist; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
  - if [[ $PHPCS_TEST ]]; then composer validate; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi